### ISSUE TITLE
Having problem with ACM ICPC Code

### ISSUE THREAD

**Issue by ritikasarkar18** [PratikGarai/Coding-Challenges#1]
The commented out code under Hackerrank is to be reviewed and mistakes need to be pointed out.

**Comment by PratikGarai** [comment]
will look into it

**Comment by PratikGarai** [comment]
N=list(map(int,input().split()))
n=N[0]
m=N[1]
l=[]
max=0
ppl = 1
for i in range(n):
    l.append(int(input(),2))
for i in range(n-1):
    for j in range(i+1, n):
        cnt_1 = 0
        for k in bin(l[i]|l[j])[2:]:
            if k=='1':
                cnt_1 += 1
        if i!=j  and max<cnt_1:
            max= cnt_1
            ppl = 1
        elif i!=j and max==cnt_1:
            ppl += 1
            
print(max)
print(ppl)

**Comment by PratikGarai** [comment]
This is the code.

**Comment by PratikGarai** [comment]
![image](https://user-images.githubusercontent.com/58355527/94921352-ce436300-04d5-11eb-9bde-e6d99658d939.png)


This is the code.

Link : https://www.hackerrank.com/challenges/acm-icpc-team/problem

**Comment by PratikGarai** [comment]
The mistakes were :
1. The objective of the problem was to find out the maximum number of topics a team could cover. That means in binary representation, the maximum number of 1's in a number. However, maximum number of 1 in binary representation doesn't necessarily mean a higher value in decimal. Example :
    binary of 8 : 1000   =>  only a single 1
    binary of 7 : 0111   =>  three 1's
your approach followed that " greater 1's = greater number ". The loop in line 12 is the correction for that.

2. The code was still giving TLE and needed to be improved. So the following things were done:
    i.  The limits of the loops was changed. Since all possible 2 man teams should be formed _irrespective_ of the  order, a semi inner loop shall generate all possible 2 element interactions. This will also save the _**i!=j**_ comparison at each iteration.
    ii.  Instead of storing results in a by generating a list ( which adds a lot of overhead ) , the max result can be directly stored as an integer. If a team is found with skills better than anyone else, the _ppl_ variable is initialized to 1, as it is the only team till then. If others are found with equal skill, this variable is incremented.

**Comment by PratikGarai** [comment]
If your doubts are cleared then you may close the issue. 👍🏿
